name: Check for array variables
on:
  workflow_dispatch:

jobs:
  printArray:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        users:${{fromJson(vars.users)}}
    steps:
      - name: Print vairables
        run: echo ${{matrix.users}}