name: Check for array variables
on:
  workflow_dispatch:

jobs:
  printArray:
    runs-on: ubuntu-latest
    environment: dev
    strategy:
      matrix:
        users:${{vars.users}}
    steps:
      - name: Print vairables
        run: echo ${{matrix.users}}