name: Check for array variables
on:
  workflow_dispatch:

env:
  users: ${{fromJson(vars.users)}}

jobs:
  printArray:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     users: ${{ fromJson(vars.users) }}
    steps:
      - name: Print vairables
        run: echo ${{env.users}}

# store users array in repo vairalbes, this wont work if we store them in environment variables
# fromJson ? each environment variable is stored as string even if we store them as ['a','b']