name: Backup job for every 15 minutes

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  BackUp:
    runs-on: ubuntu-latest
    steps:
      - name: Just print time
        run: echo "Sample job $(date)"

