name: Deployment

on:
  workflow_dispatch:
    inputs:
      ApprovalForDeployment:
        description: "Needs approval"
        required: true
        type: boolean
  repository_dispatch:

jobs:
  CreateBuild:
    runs-on: ubuntu-latest
    steps:
      - name: CreateBuild
        run: echo "CreatedBuild"

  RunTests:
    needs: CreateBuild
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: echo "Tests passed"
  
  DeployWithApproval:
    needs: RunTests
    runs-on: ubuntu-latest
    if: ${{ inputs.ApprovalForDeployment }}
    steps:
      - name: Deploy
        run: echo "Deploy code"
    environment: prod

  DeployWithoutApproval:
    needs: RunTests
    runs-on: ubuntu-latest
    if: ${{ !inputs.ApprovalForDeployment }}
    steps:
      - name: Deploy
        run: echo "Deploy code"