name: Deployment

on:
  workflow_dispatch:
    inputs:
      ApprovalForDeployment:
        description: "Needs approval"
        required: true
        type: boolean

      sampleString:
        description: "Just to experiment reading"
        required: true
        type: string

      sampleNumber:
        description: "Reading number"
        required: true
        type: number

      sampleOptions:
        description: "Reading options"
        required: true
        type: choice
        options:
          - option1
          - option2
          - option3
        default: option3

  repository_dispatch:

jobs:

  PrintTheReadedData:
    runs-on: ubuntu-latest
    steps:
      - name: Print the triggered user
        run: echo ${{ github.actor }}
      - name: print the values
        run: |
          echo "Print needs approval ${{ inputs.ApprovalForDeployment }}"
          echo "Print needs approval ${{ inputs.sampleString }}"
          echo "Print needs approval ${{ inputs.sampleNumber }}"
          echo "Print needs approval ${{ inputs.sampleOptions }}"
  CreateBuild:
    runs-on: ubuntu-latest
    steps:
      - name: CreateBuild
        run: echo "CreatedBuild"

  RunTests:
    needs: CreateBuild
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: echo "Tests passed"
  
  DeployWithApproval:
    needs: RunTests
    runs-on: ubuntu-latest
    if: ${{ inputs.ApprovalForDeployment }}
    steps:
      - name: Deploy
        run: echo "Deploy code"
    environment: prod

  DeployWithoutApproval:
    needs: RunTests
    runs-on: ubuntu-latest
    if: ${{ !inputs.ApprovalForDeployment }}
    steps:
      - name: Deploy
        run: echo "Deploy code"