name: Sample Environment variables and secrets

on:
  workflow_dispatch:

jobs:
  WorkFlowForEnvironment:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - run: echo ${{secrets.RepoSecret}}
      - run: echo ${{vars.RepoVariable}}