name: Injecting Env file to exp folder

on:
  workflow_dispatch:

jobs:
  exp:
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - name: checkout to frontend folder
        uses: actions/checkout@v4

      - name: Set up node js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: install dependencies
        run: |
          cd exp
          npm ci
      
      - name: Inject variable to env file
        run: |
          echo "VITE_V1=${{secrets.VITE_V1}}">exp/.env
          echo "VITE_V2=${{vars.VITE_V2}}">>exp/.env
        
      - name: Build
        run: |
          cd exp
          npm run build

      - name: print env file
        run: cat exp/.env      