name: Pass data between jobs and steps

on:
  workflow_dispatch:

jobs:
  store:
    runs-on: ubuntu-latest
    outputs:
      variable1: ${{steps.v1.outputs.a}}
      variable2: ${{steps.v2.outputs.b}}
    steps:
      - name: Sotre variable 1
        id: v1
        run: echo "a=Thirumalesh">>$GITHUB_OUTPUT

      - name: Store variable 2
        id: v2
        run: echo "b=Kumar">>$GITHUB_OUTPUT

      - name: Print variable 1
        run: echo "Vairable 1 is ${{steps.v1.outputs.a}}"

      - name: Print variable 2
        run: echo "Variable 2 is ${{steps.v2.outputs.b}}"

  read/access:
    needs: store
    runs-on: ubuntu-latest
    steps:
      - name: Print variable 1
        run: echo "Vairable 1 is ${{needs.store.outputs.variable1}}"
      
      - name: Print variable 2
        run: echo "Vairable 2 is ${{needs.store.outputs.variable2}}"